name: Test using Conda environments

on: [push, pull_request]

jobs:
  TestConda:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        deps:
          - "python=3.6 geos=3.6 numpy=1.13"
          - "python=3.7 geos=3.7 numpy=1.15"
          - "python=3.8 geos=3.8 numpy=1.17"
          - "python=3.8 geos numpy"
        conda-channel: ['defaults']

        # include conda-forge for latest versions of GEOS / numpy
        include:
          - deps: "python=3.8 geos numpy"
            conda-channel: 'conda-forge'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: false
          conda-channels: ${{matrix.conda-channel}}

      - name: Setup Environment
        shell: bash
        run: |
          conda env create --name test ${{matrix.deps}}
          source activate test
          python -V
          conda info
          conda list

      # set GEOS paths for Windows
      - name: Set GEOS library / include folders
        shell: bash
        if: contains(matrix.os, 'windows')
        run: |
          echo "GEOS_LIBRARY_PATH=C:\\Miniconda\\envs\\test\\Library\\lib" >> $GITHUB_ENV
          echo "GEOS_INCLUDE_PATH=C:\\Miniconda\\envs\\test\\Library\\include" >> $GITHUB_ENV

      - name: Build and install PyGEOS
        shell: bash
        run: |
          source activate test
          pip install -e .[test] --no-deps -v

      - name: Run tests
        shell: bash
        run: |
          source activate test
          pytest --doctest-modules
