name: Test using Conda environments

on: [push, pull_request]

jobs:
  TestConda:
    name: ${{ matrix.os }} - Python ${{ matrix.python }} (conda ${{ matrix.channel || 'default' }}), GEOS ${{ matrix.geos }}, numpy ${{ matrix.numpy }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: ['']
        dev: [false]
        geos: ['geos']
        numpy: ['numpy']
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: false
          conda-channels: ${{ matrix.channel }}
          python-version: ${{ matrix.python }}

      - name: Setup Environment
        shell: bash
        run: |
          conda create --name test python=${{ matrix.python}} conda pytest ${{ matrix.geos }} ${{ matrix.numpy }}
          source activate test
          python -V
          conda info
          conda list

      # set GEOS paths for Windows
      - name: Set GEOS library / include folders
        shell: bash
        if: contains(matrix.os, 'windows')
        run: |
          echo "GEOS_LIBRARY_PATH=C:\\Miniconda\\envs\\test\\Library\\lib" >> $GITHUB_ENV
          echo "GEOS_INCLUDE_PATH=C:\\Miniconda\\envs\\test\\Library\\include" >> $GITHUB_ENV

      - name: Build and install PyGEOS
        shell: bash
        run: |
          source activate test
          pip install -e . --no-deps -v

      - name: Run tests
        shell: bash
        continue-on-error: ${{ matrix.dev }}
        run: |
          source activate test
          pytest --doctest-modules
