name: Test using Conda environments

on: [push, pull_request]

jobs:
  TestConda:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        env:
          - ci/envs/py36-geos36.yml
          - ci/envs/py37-geos37.yml
          - ci/envs/py38-geos38.yml
          - ci/envs/py38-geos-latest.yml
          - ci/envs/py38-geos-latest-conda-forge.yml
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: false

      - name: Setup Environment
        shell: bash
        run: |
          conda env create -f ${{ matrix.env }}
          source activate test
          python -V
          conda info
          conda list

      # set GEOS paths for Windows
      - name: Set GEOS library / include folders
        shell: bash
        if: contains(matrix.os, 'windows')
        run: |
          echo "GEOS_LIBRARY_PATH=C:\\Miniconda\\envs\\test\\Library\\lib" >> $GITHUB_ENV
          echo "GEOS_INCLUDE_PATH=C:\\Miniconda\\envs\\test\\Library\\include" >> $GITHUB_ENV

      - name: Build and install PyGEOS
        shell: bash
        run: |
          source activate test
          pip install -e . --no-deps -v

      - name: Run tests
        shell: bash
        continue-on-error: ${{ endsWith(matrix.env, 'conda-forge.yml') }}
        run: |
          source activate test
          pytest --doctest-modules
